server:
    port: 8084 #应用服务端口
    tomcat:
        uri-encoding: utf-8
spring:
    application:
        name: oasys #应用服务名称
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/OA?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
        username: root
        password: root
#
#        secondary:
#            driver-class-name: com.mysql.cj.jdbc.Driver
#                url: jdbc:mysql://localhost:3306/static?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
#                username: root
#                password: root

#        type: com.alibaba.druid.pool.DruidDataSource
#        druid:
#            OA:
#              driver-class-name: com.mysql.cj.jdbc.Driver
#              url: jdbc:mysql://localhost:3306/OA?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
#              username: root
#              password: root
#              initialSize: 5
#              minIdle: 5
#              maxActive: 20
#
#            STATIC:
#              driver-class-name: com.mysql.cj.jdbc.Driver
#              url: jdbc:mysql://localhost:3306/static?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
#              username: root
#              password: root
#              initialSize: 5
#              minIdle: 5
#              maxActive: 20


mybatis-plus:
    typeAliasesPackage: com.songjing.oasys.**.entity
    configuration:
        log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
#            # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
#            mapper-locations: classpath:/mapper/*Mapper.xml
#            #实体扫描，多个package用逗号或者分号分隔
#            global-config:
#                #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#                id-type: 0
#                #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#                field-strategy: 2
#                #驼峰下划线转换
#                db-column-underline: true
#                #mp2.3+ 全局表前缀 mp_
#                #table-prefix: mp_
#                #刷新mapper 调试神器
#                refresh-mapper: true
#                #数据库大写下划线转换
#                #capital-mode: true
#                #逻辑删除配置（下面3个配置）
#                logic-delete-value: 4
#                logic-not-delete-value: 0
#            configuration:
#                #配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
#                map-underscore-to-camel-case: true
#                cache-enabled: false
#                #配置JdbcTypeForNull, oracle数据库必须配置
#                jdbc-type-for-null: 'null'
